### ISSUE TITLE
Templating in Rails 4

### ISSUE THREAD

**Issue by MrHubble** [argerim/select2-rails#101]
Previously in Rails 3.2 I successfully implemented templating with code:

````erb
//.js.erb
function format(image) {
    var image_path = "<%= asset_path('" + image.id.toLowerCase() +"') %>"
    return "<img class='flag' src='" + image_path + "' />";
}
````

Since upgrading to Rails 4 this no longer works and I will get the error:
> couldn't find file '" + image.id.toLowerCase() + "'

I assume this is because my erb is being called before my js, therefore it has no image name to look for. I don't know why this worked in Rails 3.2 though.

Is there a fix for implementing templating in Rails 4 with select2?

**Comment by rmicbla** [comment]
try:
<%= asset_path(image.id.downcase) %>
