### ISSUE TITLE
ui-select2 broken by jquery-rails v4.0.0 update

### ISSUE THREAD

**Issue by colinvella** [argerim/select2-rails#108]
I recently ran a "bundle update" on a project I'm working on and this broke the rendering of the ui-select2 dropdown component. After an extensive trial and error session I pinpointed the problem to jquery-rails updating from 3.1.2 to 4.0.0. For the time being I solved it by binding the gem to a specific version as in:
```ruby
gem 'jquery-rails', '3.1.2'
```
I don't know if this is an issue with ui-select2 (the related gems angular-ui-select2-rails and select2-rails haven't changed in the update AFAIK) or something broke in jquery-rails v4.0.0.

**Comment by simi** [comment]
We can't do nothing with changes in another gems. :(
