### ISSUE TITLE
Select2 4.0

### ISSUE THREAD

**Issue by kevin-brown** [argerim/select2-rails#109]
We're in the process of finalizing the 4.0 release and are aiming to have it done by the end of this month at the latest.

https://select2.github.io/

Since I'm not very familiar with this plugin, I can't really judge how easy it is going to be to migrate over to the new version.

**Comment by chrisjacob** [comment]
:+1: @kevin-brown the select2-rails gem doesn't look very complicated. It would be great if you were able to submit a PR with the v4 updates (or possibly ask for write access to this repo to keep the Rails community up-to-date with your new releases). Really excited by the re-write you've been working on - keep up the great work!

**Comment by tricknotes** [comment]
:+1: It might be a beta version of select2-rails .
I'm happy if it would be released.

**Comment by yoonsy** [comment]
[select2 v4.0.0-rc1 released!](https://github.com/select2/select2/releases/tag/4.0.0-rc.1) :)

**Comment by sn3p** [comment]
[v4.0.0-rc.2](https://github.com/select2/select2/releases/tag/4.0.0-rc.2) as well

**Comment by itsryandrake** [comment]
Will Select2 be updated to support v4? I am looking forward to the update!

**Comment by allenwlee** [comment]
+1

**Comment by sengenbe** [comment]
+1

**Comment by cnikolajsen** [comment]
+1

**Comment by risinglf** [comment]
+1

**Comment by stephendolan** [comment]
+1

**Comment by dutgcom** [comment]
+1

**Comment by maurosbu** [comment]
+1

**Comment by hackeron** [comment]
+1 - please upgrade to version 4.0 :)

**Comment by mmack** [comment]
+1

**Comment by dedman** [comment]
+1 :)

**Comment by IgorDobryn** [comment]
+1, please, upgrade it to 4.0

**Comment by calfzhou** [comment]
+1 please!!!

**Comment by eikes** [comment]
# Gemfile

source 'https://rails-assets.org/' do
  gem 'rails-assets-select2', '~> 4.0.0'
end

**Comment by plentz** [comment]
already fixed
