### ISSUE TITLE
styling issues when used inside bootstrap modal

### ISSUE THREAD

**Issue by bertBruynooghe** [argerim/select2-rails#110]
See added image.
![modal](https://cloud.githubusercontent.com/assets/500119/5919146/2d9b379c-a631-11e4-99dd-f8e5274d1ea9.png)
Had to add the following to the css:

    form .modal .form-group div.select2-container{
      padding-left: 0;
      padding-right: 0;
    }

**Comment by bertBruynooghe** [comment]
![modal](https://cloud.githubusercontent.com/assets/500119/5919141/145456c4-a631-11e4-9306-19b9d248bb46.png)

**Comment by simi** [comment]
Do you think this is related to this repo? I think this can be upstream or custom style problem.

**Comment by kevin-brown** [comment]
At this point, it's a 1.5 year old ticket on a legacy version of Select2. It can probably be closed off.

**Comment by bertBruynooghe** [comment]
Haven't updated the code since then. It's probably safe to close the ticket. If I come across that code again, I'll have another look and recreate the ticket if necessary.
