### ISSUE TITLE
SASS autoloading errors - unable to load select2.scss

### ISSUE THREAD

**Issue by passbe** [argerim/select2-rails#111]
Running version 3.5.9.3 I receive the following error messages when running rspec:

```
WARN: tilt autoloading 'sass' in a non thread-safe way; explicit require 'sass' suggested.

  An error occurred in an after hook
    ActionView::Template::Error: cannot load such file -- sass
  (in /Users/test/.rvm/gems/ruby-2.0.0-p353/gems/select2-rails-3.5.9.3/vendor/assets/stylesheets/select2.scss)
    occurred at /Users/test/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
```

On a specific view test:

```
ActionView::Template::Error:
       cannot load such file -- sass
         (in /Users/test/.rvm/gems/ruby-2.0.0-p353/gems/select2-rails-3.5.9.3/vendor/assets/stylesheets/select2.scss)
```

I do not have the `sass` gem installed, I'm currently using `less` for other gems. Has `sass` become a dependancy for this project?

Any help would be appreciated.

**Comment by magedmakled** [comment]
@passbe , I'm also getting that error, did you find a solution?

**Comment by CedricLor** [comment]
@passbe @magedmakled Hi guys,  I am getting the same error. 

Did you ever find the solution ?

Thanks

**Comment by magedmakled** [comment]
@CedricLor I ended up just using the `select2` JS and CSS instead of the gem.

**Comment by CedricLor** [comment]
How sad. I'll try to get an answer from the lead dev on this. They have gitter channel where he is pretty active. Thank you!!

**Comment by Uysim** [comment]
I get the same error

**Comment by simi** [comment]
sass was removed from this repository, closing...
