### ISSUE TITLE
Cannot read property 'locales' of undefined

### ISSUE THREAD

**Issue by IgorBabkin** [argerim/select2-rails#112]
I have that error in my rails application.

My application.js is

> \#= require select2
> \#= require select2_locale_ru

And error raises here

> fn.select2.locales.ru

**Comment by wrpinheiro** [comment]
Hello @IgorBabkin, did you find a solution for this error? I'm experiencing the same problem with version 3.5.9.3.

Thank you.

**Comment by IgorBabkin** [comment]
Yeah, there was problem with compressing through Sprockets on my machine.
Not in library

2015-03-31 19:43 GMT+03:00 Wellington Ricardo Pinheiro <
notifications@github.com>:
