### ISSUE TITLE
License of images and stylesheets

### ISSUE THREAD

**Issue by balasankarc** [argerim/select2-rails#115]
What are the license details of images (the three png files) and stylesheets (the two css files) bundled with this gem?

**Comment by kevin-brown** [comment]
If you are referring to the Select2 images and stylesheets, then it should all be under the same dual-license.

https://github.com/select2/select2/blob/stable/3.5/LICENSE

**Comment by balasankarc** [comment]
Does this include select2-bootstrap.css also??

https://github.com/argerim/select2-rails/blob/master/vendor/assets/stylesheets/select2-bootstrap.css

**Comment by kevin-brown** [comment]
`select2-bootstrap.css` appears to be from https://github.com/t0m/select2-bootstrap-css (here's the [SCSS file for reference](https://github.com/t0m/select2-bootstrap-css/blob/bootstrap3/lib/select2-bootstrap.scss).

The license there is MIT.

https://github.com/t0m/select2-bootstrap-css/blob/bootstrap3/LICENSE
