### ISSUE TITLE
Rails Assets

### ISSUE THREAD

**Issue by besi** [argerim/select2-rails#116]
Hy there. I am using [Rails Assets](https://rails-assets.org) for some of my projects. So I was wondering which approach I should use:

1. Using `gem 'select2-rails'`
2. Using 

        source 'https://rails-assets.org' do
            gem 'rails-assets-select2'
        end

From the outside it seems that both solutions are both "simple wrappers" for the HTML+JS libraries. So I am wondering if select2-rails is adding additional functionality other than wrapping the library.

**Comment by lunks** [comment]
No, we're just wrapping. The main difference between both is that `select2-rails` require us to manually repackage `select2`. Rails-assets allows you to upgrade to a new version when the javascript library author releases a new one.
