### ISSUE TITLE
select2 bootstrap3 styling

### ISSUE THREAD

**Issue by sivagollapalli** [argerim/select2-rails#117]
Thanks for awesome gem. I have included the gem as per documentation. But I think it didn't follows bootstrap 3 syling as specified https://fk.github.io/select2-bootstrap-css/ . Is there the gem needs to update the css or am I including wrong version?

**Comment by sivagollapalli** [comment]
I have solved this problem. It has included wrong version. Instead `3.5.9.3` it has installed `3.5.9.1`. Do we need to specify exact version for `select2-rails` to get updated bootstrap styling?

**Comment by simi** [comment]
You need to point to minimal version you need to use.
