### ISSUE TITLE
Tags error

### ISSUE THREAD

**Issue by xufeiyun** [argerim/select2-rails#123]
when I use below codes:
    $("select#the_select_id").select2({
      placeholder: Pease type or select an item here...",
      allowClear: true,
      tags: true
    });

I got below errors:
Uncaught Error: Option 'tags' is not allowed for Select2 when attached to a <select> element.

Why it doesn't support tags option?

select2-rails version:  3.5.9.3

**Comment by vijay15793** [comment]
Same problem

**Comment by simi** [comment]
I think this is solved in 4.0 version. Anyway please open select2 questions somewhere in [upstream community](https://select2.github.io/community.html).
