### ISSUE TITLE
Select2-rails version 4

### ISSUE THREAD

**Issue by sadiqmmm** [argerim/select2-rails#130]
What are the breaking changes, features of select2-rails version 4, compare to select2-rails version 3.

Thanks

**Comment by pdambrauskas** [comment]
https://select2.github.io/announcements-4.0.html

**Comment by simi** [comment]
This is related to upstream. You can still use 3.5 with select2-rails (3.5.x gem or 3-5-stable github branch).

**Comment by nilbus** [comment]
In my experience, in most cases, you'll need to update your code to be
compatible with the new library.​ Plenty has changed.
