### ISSUE TITLE
How can i use select2.full.js / select2.full.min.js?

### ISSUE THREAD

**Issue by PlugIN73** [argerim/select2-rails#131]
From select2 4.0 they have two different builds:

    Standard (select2.js / select2.min.js)
    Full (select2.full.js / select2.full.min.js)	

How can i use full build? I didn't find it in this repo.

**Comment by plentz** [comment]
+1

**Comment by Hirurg103** [comment]
+1

**Comment by simi** [comment]
Full build is available in master right now and will be released soon.
