### ISSUE TITLE
siimple_form + acts_as_taggable_on + selec2

### ISSUE THREAD

**Issue by Svashta** [argerim/select2-rails#132]
Hi,

i am trying to implement a select2-rails with acts_as_taggable_on and simple_form for few days now and feel really stupid, because whatever i do i can't get it to work.

I have two problems it gets down to:
- either a select2 is working, but only one value is posted
- or select2 doesn't show values to be able to choose from (but i can actually see them before select2 kicks in on the input)

Is  anyone so kind and show how to do it in JS and view?
This is really frustrating as it should be quite simple.
I just don't get it anymore.

**Comment by mmplisskin** [comment]
Not sure if this helps but this is how I did it. Still trying to figure out the edit action. 

```
  <%= f.select :tag_list, options_for_select(options_for_tags), {}, { multiple: true, :style => "width:500px;"} %>
```

And in the JS

```
$( "#event_tag_list" ).select2({
  createSearchChoice: function() { return null; },
  tokenSeparators: [',', ' '],

})

```

**Comment by kuboon** [comment]
this is my code working.
https://gist.github.com/kuboon/f692d9a844c0ff5877c8

**Comment by Tab10id** [comment]
We implement gems for automatic initialize select2 on several form builders (includes SimpleForm)
https://github.com/Loriowar/auto_select2
https://github.com/tab10id/simple_form_auto_select2
First gem is a basic library form automatic initialize select2
Second gem implement Select2Input class for simple_form
All you need is:
```ruby
f.select :tag_list, as: :select2, ......
```

**Comment by heinrichhanekom** [comment]
This seems to be working 

```ruby
<%= f.association :tag_list do %>
	<%= f.select :tag_list, options_for_select(ActsAsTaggableOn::Tag.all, resource.tag_list), {}, {class: 'select2', multiple: true, :style => "width:100%;"} %>
<% end %>
```

It includes the edit action.
