### ISSUE TITLE
Rename of select2.scss to css causing problems?

### ISSUE THREAD

**Issue by corroded** [argerim/select2-rails#135]
Hi just wanted to ask if the rename of the `select2.scss` file to `select2.css` was deliberate or a typo. We were using the 3.5.2 version and recently just updated to v4. The problem is, using `@import 'select2'` breaks the tests (really not sure why) - it says `Sass::SyntaxError - File to import not found or unreadable: select2.`

When I did a bundle open and renamed the file to scss, the tests passed. I don't think forking this and just renaming it to scss would be a good solution for us. If it's just a typo, I can rename and submit a PR, but if it was deliberate (I'm guessing because of this: https://github.com/argerim/select2-rails/issues/99), is there a good solution for this besides just forking? Thanks!

P.S.

We are using foundation for apps as our framework so we needed to do `@import 'select2'` so our overrides can work. Doing `*= require 'select2'` didn't load the base styles.

**Comment by nilbus** [comment]
I believe this change was unintentional. Prior to 36121855aa3727400598b6b0bf4c12d31a690fea, `select2.css` was downloaded as `select2.scss`, which allowed sass to `@import 'select2'`. I believe this change was unintentional. @frodrigo, it would be helpful if you could confirm.

**Comment by nilbus** [comment]
Despite that extension change to `.css`, in my app, I am still able to `@import "select2"`. I'm on sass-3.4.14 and sass-rails-3.2.6.

@corroded I assume it also breaks in your app, not just your tests? You're also generally not using `require`, right?

**Comment by corroded** [comment]
@nilbus We're using sass 3.4.18 and sass-rails 5.0

That's the funny thing, it works in our app, the test fails though, and that test is a simple `get '/' integration test. And yes, not using require, we're using @import 'select2' as well.

**Comment by nilbus** [comment]
I ran into this issue today. We have several apps that use a rails engine UI gem that depends on select2-rails.

**We found that it's now necessary to `require 'select-rails'` to make `@import 'select2'` work now.**

This require happens implicitly when your Gemfile contains `gem 'select2-rails'`, but if it's loaded as a dependency of something (as in my case with the gem), you'll need to either add it to your Gemfile or `require 'select2-rails'` in an initializer.

Why did this work before without requiring select2-rails? I'm not sure, but maybe that's some magic the sass gem does.

@corroded Will you please check if `require 'select-rails'` or `gem 'select2-rails'` in the Gemfile resolves this problem for you? If you're using a gem or engine that uses select2-rails, that would be the best place to add a require statement.

**Comment by nilbus** [comment]
oops, I meant `require 'select2-rails'`.

**Comment by corroded** [comment]
Yes, we are using select2 in a [rails engine](https://github.com/aelogica/express_admin/blob/master/lib/express_admin/engine.rb#L7). It is in the engine's `engine.rb`. We have another rails engine(say, engineB) that requires express_admin and it's integration test is where it fails.

We have tried adding `gem 'select2-rails' in engineB's Gemfile and also tried adding `require 'select2-rails'` in `test/dummy/config/initializers/select2.rb` to no avail. I am also starting to think that this may be a problem with sass or sass-rails, since the initial solution, which is to just rename the css file to scss solves it. I mean, shouldn't they just be the same? I am assuming they actually check if the file has scss syntax or not, no matter if the extension is css or scss.

**Comment by nilbus** [comment]
I don't know about the other things you tried, but the line [you linked](https://github.com/aelogica/express_admin/blob/master/lib/express_admin/engine.rb#L7) is just like the one we used to get it to work. I'm not sure.

**Comment by corroded** [comment]
Thanks though. So should I send a PR to rename it to scss? If you can look into that link again, we have bourbon and foundation and their assets are working correctly (I think this is why we arrived to the conclusion that the extension must be `.scss` instead of just `.css`)

**Comment by corroded** [comment]
@nilbus looks like our tests are passing now. Still not sure about what fixed it - our require clause was already there before the errors and that wasn't what we changed. I'll close this now unless @frodrigo says the filename change was unintentional?

**Comment by nilbus** [comment]
Even if unintentional, I hesitate to rename back to scss, because it's not scss, and because the change may likely fix #99.

**Comment by frodrigo** [comment]
I rename it just because it's no more scss content.

**Comment by nilbus** [comment]
I think this can stay as-is then. @simi Do you think it's worth mentioning in the Readme that you must `require 'select2-rails'` when using this gem in a rails engine?

**Comment by strzibny** [comment]
I had to change my code to:
```
@import "select2.css";
```
Then it works again.

**Comment by simi** [comment]
@nilbus feel free to mention that in README. But I think that's nothing select2-rails specific, is it?

**Comment by nilbus** [comment]
Hm, probably not. Good point.

**Comment by duarte171183** [comment]
my solution its add in the file application.scss

```
@import "select2.css";
@import "select2-bootstrap";
```
thanks @strzibny
