### ISSUE TITLE
Uncaught Error: No select2/compat/inputData

### ISSUE THREAD

**Issue by sajjadmurtaza49** [argerim/select2-rails#137]
$('.single-field').each ->
    $(this).select2
      data: $(this).data('options')
      width: "252px"
      multiple: false

**Comment by sajjadmurtaza49** [comment]
I found the solution. 
This problem in select2-rails (4.0.0)
Now am using select2-rails (3.5.9.1) its working fine for me.

**Comment by nilbus** [comment]
According to this [select2 user group post](https://groups.google.com/d/msg/select2/yifYbU1HPOY/elnBFC5-dLMJ):

> Support for `<input />` tags is only available in the full builds of Select2. You should be using "select2.full.js" and we should be providing a better error message about it.

This will be available (hopefully) in the next version of this gem, once #134 is merged.
