### ISSUE TITLE
Not getting placeholder

### ISSUE THREAD

**Issue by mentalia** [argerim/select2-rails#138]
Previously the select2 was getting the placeholder from the placeholder tag in the select, but now it doesn't work.

**Comment by nilbus** [comment]
Could you provide​ your specific markup example?

**Comment by bengalamx** [comment]
It is a basic markup, but then my select appears empty:

> main.js
```javascript
$('select.select2').select2();
```

> _form.html.erb
```ruby
<%= simple_form_for model do |f| %>
  <%= f.input :name, placeholder: 'Who are you?' %>
  <%= f.input :category_id, input_html: { class: 'select2' }, collection: @categories, placeholder: 'Please select the category you want' %>
  <%= f.submit  %>
<% end %>
```

My fix for now is:

```javascript
$('select.nice').select2({
  placeholder: '- Select -'
});
```

**Comment by nilbus** [comment]
Try using the data-placeholder attribute instead.

    "data-placeholder" => "…"

or

    data: {placeholder: "…"}

**Comment by mentalia** [comment]
Yep! It works with `data-placeholder`, so in my code i added `data: { placeholder: '...' }` this way:

```ruby
<%= simple_form_for model do |f| %>
  <%= f.input :name, placeholder: 'Who are you?' %>
  <%= f.input :category_id, input_html: { class: 'select2', data: { placeholder: 'Please select the category you want' } }, collection: @categories %>
  <%= f.submit  %>
<% end %>
```

Thanks for your help @nilbus, hope there is a fix soon...

**Comment by nilbus** [comment]
Using the input tag's HTML5 `placeholder` attribute was never a documented feature of select2, though at least with `<input>` tags, it worked with version 3.5. In 4.0 now that only `<select>` tags are preferred (which don't support a `placeholder` attribute in HTML5), I doubt they will add support for that. Use the `data-placeholder` attribute as the documentation suggests.

This issue can be closed, as this rails plugin can not add features to the select2 library.

**Comment by kevin-brown** [comment]
> In 4.0 now that only `<select>` tags are preferred (which don't support a placeholder attribute in HTML5)

This is correct, and Select2 works against the JS DOM (instead of HTML attributes) so it doesn't have access to the (incorrectly placed) `placeholder` attribute even if it is present.

> I doubt they will add support for that. Use the `data-placeholder` attribute as the documentation suggests.

Using `data-placeholder` is the recommended solution here. Or do it within the JS if you have direct access there and don't want to place it within the HTML.

**Comment by simi** [comment]
Next time please open select2 issues in [upstream](https://github.com/select2/select2) repository. This repo is just wrapper for Rails asset pipeline and only wrapper problems should be reported here.
