### ISSUE TITLE
Internationalization not working

### ISSUE THREAD

**Issue by bengalamx** [argerim/select2-rails#139]
In my application.js i have:

//= require select2
//= require select2_locale_es

And still is showing me everything in english...

**Comment by link82** [comment]
I'm having a similar issue: if i import multiple locale files it will consider only the last one.

//= require select2_locale_en
//= require select2_locale_it
//= requireselect2_locale_de

i.e. will output always strings in german.

**Comment by danieldocki** [comment]
+1

**Comment by danieldocki** [comment]
@bengalamx @link82 

In version 4 of select2, need set language:

```
    $('select').select2({
      theme: "bootstrap",
      language: "pt-BR"
   })
```

**Comment by PeterMozesMerl** [comment]
@bengalamx Thank you. 

This should be displayed in the README. I wasted an hour on trying to make the I18n work using either this gem or the upstream version. I just wanted to report it as an issue.

**Comment by bengalamx** [comment]
Working with `language: "es"`, hope it can upgrade to work with rails `config.i18n.default_locale`

**Comment by simi** [comment]
```erb
<% # layout.html.erb %>
<html lang="<%= I18n.locale %>">
...
</html>
```

```javascript
// application.js
$('select').select2({
  theme: "bootstrap",
  language: $('html').attr('lang')
})
```

should be enough.

**Comment by Leoxxid** [comment]
Work for me changing //= require select2  for //= require select2_locale_pt-BR
