### ISSUE TITLE
Uncaught TypeError when click to clear button

### ISSUE THREAD

**Issue by mayatskiy** [argerim/select2-rails#140]
<pre>
select2-rails v4.0.0
</pre>
When I apply select2 with allowClear option, I have
<pre>
Uncaught TypeError: Cannot read property 'id' of undefined
 S2.define.AllowClear._handleClear	
 S2.define.Utils.Decorate.calledMethod
 (anonymous function)
 jQuery.event.dispatch
 jQuery.event.add.elemData.handle
</pre>
when click to clear button.

**Comment by DemidenkoAndrey** [comment]
I have 
`TypeError: undefined is not an object (evaluating 'this.placeholder.id')`

**Comment by kevin-brown** [comment]
This usually means you are using the `allowClear` option without the `placeholder` option. If you set `debug: true` when initializing Select2, there should be a warning about this in the console.

**Comment by leesmith** [comment]
This was exactly my problem as well. Thanks for the tip @kevin-brown
