### ISSUE TITLE
Issue with using oldMatcher

### ISSUE THREAD

**Issue by bitsapien** [argerim/select2-rails#146]
I'm upgrading my application to use select2 4.0.0 from select2 3.5.5. I use a matcher function, and have re-written my code as explained in 
https://select2.github.io/announcements-4.0.html#new-matcher
The select2 script resides in assets/application.js. I get the following error : ```Error: undefined missing select2/compat/matcher```
I do not understand whats going wrong. Is it something to do with the require path not resolving ?

**Comment by kevin-brown** [comment]
It sounds like you are not using the full build of Select2 (`select2.full.js`).

**Comment by simi** [comment]
Exactly! FYI Full build is now supported in master (and I'll try to release new version A$AP).

**Comment by harrysainipur** [comment]
Thanks, it works for me.
