### ISSUE TITLE
Can not change to Japanese language

### ISSUE THREAD

**Issue by nhieu92** [argerim/select2-rails#151]
Hi. I want to use select2 with Japanese language but when I try to add 
`//= require select2`
`//= require select2_locale_ja`

into application.js, I got `prockets::FileNotFound`
`couldn't find file 'select2_locale_ja' with type 'application/javascript'`
Others language work fine, ex  `select2_locale_vi`,  `select2_locale_de` ...
Could someone help me? Thank you !

**Comment by simi** [comment]
Version?

**Comment by nhieu92** [comment]
@simi select2-rails (4.0.0)

**Comment by simi** [comment]
please try update to 4.0.1

**Comment by nhieu92** [comment]
@simi Worked!. Thank you bro ! :+1:
