### ISSUE TITLE
couldn't find file 'select2-full'

### ISSUE THREAD

**Issue by jocyvan** [argerim/select2-rails#154]
Hi everyone, I received this error after to update select2 from 3.5.3 to 4.0.1.
First of all, after receive this error I received this message: 

> Uncaught Error: No select2/compat/initSelection.

So I tried to require select2-full and this file could not found.
Anybody would help me?

**Comment by simi** [comment]
@jocyvan if you need full build, please use master branch (or wait until new release will be out).

**Comment by jocyvan** [comment]
Ok. Thanks.
