### ISSUE TITLE
How to check by JS or jQuery if any select2 option is selected?

### ISSUE THREAD

**Issue by PirunSeng** [argerim/select2-rails#156]

**Comment by simi** [comment]
Please open only issues related to this repository. This is not issue, but question. And also is not related to this repository.

ps: maybe [this message](https://github.com/select2/select2/issues/2929#issuecomment-97022674) will help you

**Comment by PirunSeng** [comment]
Found a solution from stackoverflow soon I posted this but forgot to save the link as reference.
Sorry for misunderstanding.
