### ISSUE TITLE
Sass::SyntaxError at / File to import not found or unreadable: select2.

### ISSUE THREAD

**Issue by kumarks1122** [argerim/select2-rails#173]
Ruby: 2.3.0
Rails: 5.1.3
Bundler: 1.15.4
ActiveAdmin: 1.1.0
ActiveAdmin_addons: 1.0.1
After updating the ActiveAdmin from 1.0.0 to 1.1.0, I am getting this error:
`Sass::SyntaxError at / File to import not found or unreadable: select2.`

**Comment by deivid-rodriguez** [comment]
Closing in favor of #5226 since it does seem like the same issue. Thanks @tf!

**Comment by ghost** [comment]
As this seems like an issue that should be resolved with the activeadmin project, as pointed to by @tf , I'll close this but please open a new issue if this is traced to a select2-rails problem.
