### ISSUE TITLE
release version to support 4.0.4?

### ISSUE THREAD

**Issue by JeremiahChurch** [argerim/select2-rails#175]
Now that select2 4.0.4 is available can a new version of the gem be cut?

https://github.com/select2/select2/blob/4.0.4/CHANGELOG.md

**Comment by skuark** [comment]
There is a PR already: #174

**Comment by OpenCoderX** [comment]
4.0.4 is released: https://github.com/argerim/select2-rails/releases/tag/v4.0.4
