### ISSUE TITLE
Add Maintainers

### ISSUE THREAD

**Issue by OpenCoderX** [argerim/select2-rails#193]
I maintain a private git repo with updated versions of select2, if you add me as a maintainer I can create new versions and push them up to this repo. @argerim

**Comment by Nitrodist** [comment]
Someone take over the maintenance of this, fr.

**Comment by OpenCoderX** [comment]
@argerim Any interest in adding another maintainer? I would be happy to contribute.

**Comment by joshm1204** [comment]
@argerim, Please allow others to maintain it if you are not.  It's a useful gem, but out of date. Thank you for building it.

**Comment by williamweckl** [comment]
@argerim +1

**Comment by OpenCoderX** [comment]
@caironoleto , @cleitonfco, @cyruscavalcante, @dannluciano, @samflores, @weldyss are any of you in contact with @argerim ? I notice you are all part of the @GuruPI org.

**Comment by williamweckl** [comment]
@OpenCoderX could you open your fork? My company would like to use it.

**Comment by caironoleto** [comment]
@OpenCoderX Nops! You can try contacting him via LinkedIn: https://www.linkedin.com/in/argerim/

**Comment by OpenCoderX** [comment]
@williamweckl If my efforts to contact @argerim fail I will, I'd like to avoid splitting the community. Lots of stars on this repo and the used by tracker says 10.4k.  @caironoleto Thanks! I'll connect with him.

**Comment by argerim** [comment]
@OpenCoderX sorry for the delay. My NotBook burned and I lost some data.
I add u as a maintainer.
