### ISSUE TITLE
Create release tags for all missing select2 versions

### ISSUE THREAD

**Issue by OpenCoderX** [argerim/select2-rails#195]

**Comment by weber-s** [comment]
Hello !
I saw in https://github.com/argerim/select2-rails/issues/193 that you are now maintener! Thank you and great news for this gem !!!
  
Do you have news for this issue ?

**Comment by ghost** [comment]
@weber-s I have created the missing tags in this github repo and am working to get access to the rubygems info (@argerim) so I can officially manage then entire release process, in the meantime you will have to point your gemfile to this repo.

**Comment by ghost** [comment]
The releases are now available on rubygems.com for install via rubygems
