### ISSUE TITLE
Move `thor` to a development dependency in 3.5.x patch version

### ISSUE THREAD

**Issue by garettarrowood** [argerim/select2-rails#199]
I have a project that is not yet ready to move to `select2-rails` 4.x, but relies on version 3.5.9.x.

Other libraries in my project rely on higher versions of `thor` that are not compatible with the `~> 0.14` restriction in the 3.5.x versions of `select2-rails`.

I see that `thor` was moved to a development_dependency in the current version of `select2-rails`. Could there be a 3.5.x release cut that simply moves this to a development dependency?

**Comment by benlangfeld** [comment]
See https://github.com/argerim/select2-rails/pull/167

**Comment by andrehjr** [comment]
3.5.11 was released with thor as a development_dependency. https://rubygems.org/gems/select2-rails/versions/3.5.11

**Comment by garettarrowood** [comment]
Resolved
