### ISSUE TITLE
Issue with turbolinks

### ISSUE THREAD

**Issue by rylwin** [argerim/select2-rails#47]
When using select2-rails with turbolinks, I see an error trying to use `.select2()` after a page is loaded with turbolinks (i.e., the first page load works fine, but the error always happens after clicking a link that causes the page to be loaded via turbolinks). The error is: 

``` js
Object [object Object] has no method 'select2' 
```

I've found that the following piece of code being executed on `page:load` prevents this error:

``` js
window.Select2 = undefined;
```

By unsetting the Select2 global, the select2 js constructs the `select2()` function again, preventing the error.

I wasn't really sure where this discussion belongs, but this seemed like a good place to start. Anybody else experiencing this issue w/ select2 and turbolinks?

**Comment by mlt** [comment]
[This might be relevant](http://stackoverflow.com/a/40768142/673826) for those suffering with TL.
