### ISSUE TITLE
IE8 throws errors when asset is compiled

### ISSUE THREAD

**Issue by fixr** [argerim/select2-rails#63]
Hi!

On IE8, when assets are precompiled for production, I'm getting <strong>"Invalid character"</strong> for select2.js and <strong>'fn.select2.defaults' is null or not an object</strong> on select2_locale_es.js. This, however, works fine on development without the compilation. I'm running rails 4 and ruby 2, and it can be reproduced <a href="http://select-2-example.herokuapp.com/">on the Heroku app example</a>.

I think it has something to do with the UTF-8 characters on the DIACRITICS constant. Any ideas?

Thanks!

**Comment by aliameen91** [comment]
Hi @camsong , i am facing the same issue, but my backend is laravel instead of rails. i am using laravel mix to compile assets. can you please shed some light on how i can fix it on laravel ?
