### ISSUE TITLE
Changelog feature request

### ISSUE THREAD

**Issue by johnjohndoe** [argerim/select2-rails#68]
Please consider providing a textual changelog so it is easier for users to see what changes from version to version.
- [Example changelog of devise](https://github.com/plataformatec/devise/blob/v3.1.1/CHANGELOG.md)
- [Example changelog of cancan](https://github.com/ryanb/cancan/blob/1.6.10/CHANGELOG.rdoc)
- [Example changelog of angular.js](https://github.com/angular/angular.js/blob/v1.1.5/CHANGELOG.md)
- [GitHub offers release notes](https://github.com/argerim/select2-rails/releases/new) ... this link only works for argerim
- [GitHub release notes example of better_errors](https://github.com/charliesome/better_errors/releases)

**Comment by simicic** [comment]
I am also curious about that. Closed without a comment?
Thanks!

**Comment by simi** [comment]
We follow upstream versioning and you can do tag diff to see changes between versions.

**Comment by extrajordanary** [comment]
> We follow upstream versioning and you can do tag diff to see changes between versions.

Cool, can you add instructions for how to do this to the readme then?
