### ISSUE TITLE
sprockets_better_error reports: Asset depends on 'select2.png' 

### ISSUE THREAD

**Issue by irobayna** [argerim/select2-rails#70]
Asset depends on 'select2.png' to generate properly but has not declared the dependency
Please add:

```
//= depend_on_asset "select2.png"`
```

to 

```
app/assets/stylesheets/select2.css.erb
```

**Comment by gfauredumont** [comment]
Hi,

Sorry about this, but I have the same error (asking for `//= depend_on_asset "select2.png"` in `select2-rails-3.5.9.3/vendor/assets/stylesheets/select2.scss`).
While looking upon this error, I arrived here, but when I checked out the file, I can't find the `depend_on` line, even in the file's history...

My guess is I have missed something...

Could you help me out ?

**Comment by gfauredumont** [comment]
So I ended up adding these lines to `select2.scss` file:
```scss
//= depend_on_asset "select2.png"
//= depend_on_asset "select2-spinner.gif"
//= depend_on_asset "select2x2.png"
```

**Comment by om-nishu-trantor** [comment]
@gfauredumont Are you sure `select2.scss` worked out ?

**Comment by gfauredumont** [comment]
Hi,
To be honnest, I don't use select2 anymore, but the problem is probably fixed by now... ;)
