### ISSUE TITLE
Hidden Accessible Span showing when dropdown clicked

### ISSUE THREAD

**Issue by paulthegeek** [argerim/select2-rails#88]
I just recently updated my gem and I am now seeing a span that is showing the amount of options in the select tag. It looks something like this:

37 results are available, use up and down arrow keys to navigate.

I am not sure how to get rid of it and I beileve this is the code that is causing it.

``` js
this.liveRegion = $("<span>", {
                    role: "status",
                    "aria-live": "polite"
                })
                .addClass("select2-hidden-accessible")
                .appendTo(document.body);
```

**Comment by geoffreymm** [comment]
I'm facing a similar issue. Just updated to version 4.0.0 and suddenly the select tag have the following class:
```
select2 select2-hidden-accessible visible
```
This cause the select to be hidden.
Just rolled back to previous version (3.5) and worked fine again.
Any clue of what is causing this?

**Comment by mintaras** [comment]
Same here.. with latest select2 v4.0.3
Select fields have "select2-hidden-accessible" class which hides the fields
