### ISSUE TITLE
Track select2 versions

### ISSUE THREAD

**Issue by benlinton** [argerim/select2-rails#95]
For version numbers I would recommend tracking select2 version numbers.  Add a forth version number for your own revisions of a given select2 version.  For example:

* At v3.5.0 of __select2.js__ =>
  * Set v3.5.0 of __select2-rails__ for initial release
* At v3.5.1 of __select2.js__ =>
  * Set v3.5.1 of __select2-rails__ for initial release
  * Set v3.5.1.1 if __select2-rails__ had a new release while using v3.5.1 of __select2.js__
  * Set v3.5.1.2 if __select2-rails__ had another new release while using v3.5.1 of __select2.js__

And so on...

**Comment by argerim** [comment]
thnx man.
I can fix in version 4.0
