### ISSUE TITLE
Bootstrap styles appears not to be respected

### ISSUE THREAD

**Issue by yourtallness** [argerim/select2-rails#98]
Hello,

I have added:

     *= require select2
     *= require select2-bootstrap

to my application.css yet the BS3 do not appear to be respected.

Worse still, some selects are now only 1-2 characters wide and impossible to use, in other words they do not adopt the width of the widest option.

Any idea what configuration I might be missing?

Thanks in advance

**Comment by jordigg** [comment]
Seems that the boostrap file is not updated. Using this one works. https://raw.githubusercontent.com/t0m/select2-bootstrap-css/bootstrap3/select2-bootstrap.css

**Comment by betomoretti** [comment]
@jordigg answer works for me. Thanks
