### ISSUE TITLE
SCSS file in vendor/assets conflicts when using less in rails

### ISSUE THREAD

**Issue by twistedR** [argerim/select2-rails#99]
If the rails project uses less instead of sass then the rails server won't load since the required gem to compile the SASS lib is not present.

**Comment by chrisjacob** [comment]
Does this not fix your issue?

```ruby
# - Select2 for rails asset pipeline (requires SASS)
gem 'sass-rails'
gem "select2-rails"
```

**Comment by twistedR** [comment]
This is more of a work around. You are loading a whole gem just for one sass file.

**Comment by nilbus** [comment]
@twistedR @yourtallness Does it work for you now with the 4.0.0 release? 4.0.0 (though I don't know about future versions) provides `select2.css` instead of `.scss`.

**Comment by simi** [comment]
sass is gone, closing
